# Generated by Django 6.1.1 on 2026-09-24 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], max_length=2, unique=True)),
                ('title_de', models.CharField(max_length=100)),
                ('title_sq', models.CharField(max_length=100)),
                ('description_sq', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.SlugField(max_length=100)),
                ('title_de', models.CharField(max_length=150)),
                ('title_sq', models.CharField(max_length=150)),
                ('objective_sq', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('unit__level__position', 'unit__position', 'position'),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='course-assets/%Y/%m/')),
                ('alt_text_sq', models.CharField(blank=True, max_length=250)),
                ('creator', models.CharField(max_length=150)),
                ('source_url', models.URLField(blank=True)),
                ('license_name', models.CharField(max_length=100)),
                ('license_url', models.URLField(blank=True)),
                ('attribution_text', models.TextField(blank=True)),
                ('acquired_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('exercise_type', models.CharField(choices=[('picture_choice', 'Picture selection'), ('translation_choice', 'Translation choice'), ('missing_word', 'Missing word'), ('word_order', 'Word ordering'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=30)),
                ('instructions_sq', models.CharField(max_length=250)),
                ('prompt_de', models.TextField(blank=True)),
                ('prompt_sq', models.TextField(blank=True)),
                ('expected_answer', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='draft', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_exercises', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson')),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_exercises', to='courses.mediaasset')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_exercises', to='courses.mediaasset')),
            ],
            options={
                'ordering': ('lesson', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.SlugField(max_length=100)),
                ('title_de', models.CharField(max_length=150)),
                ('title_sq', models.CharField(max_length=150)),
                ('summary_sq', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='courses.cefrlevel')),
            ],
            options={
                'ordering': ('level__position', 'position'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.unit'),
        ),
        migrations.CreateModel(
            name='VocabularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('german', models.CharField(max_length=200)),
                ('albanian', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('example_de', models.TextField(blank=True)),
                ('example_sq', models.TextField(blank=True)),
                ('notes_sq', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='courses.lesson')),
            ],
            options={
                'ordering': ('lesson', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExerciseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('text_de', models.CharField(blank=True, max_length=250)),
                ('text_sq', models.CharField(blank=True, max_length=250)),
                ('is_correct', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.exercise')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_options', to='courses.mediaasset')),
            ],
            options={
                'ordering': ('exercise', 'position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('exercise', 'position'), name='unique_option_position_per_exercise'), models.CheckConstraint(condition=models.Q(('text_de__gt', ''), ('text_sq__gt', ''), ('image__isnull', False), _connector='OR'), name='exercise_option_has_content')],
            },
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('lesson', 'position'), name='unique_exercise_position_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('review_status', 'draft'), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), models.Q(('review_status__in', ('reviewed', 'published')), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='exercise_review_state_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('level', 'slug'), name='unique_unit_slug_per_level'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('level', 'position'), name='unique_unit_position_per_level'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'slug'), name='unique_lesson_slug_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'position'), name='unique_lesson_position_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyentry',
            constraint=models.UniqueConstraint(fields=('lesson', 'german', 'albanian'), name='unique_vocabulary_pair_per_lesson'),
        ),
    ]
