# Generated by Django 6.1.1 on 2026-09-25 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_media_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='language_code',
            field=models.CharField(blank=True, choices=[('', 'Not language-specific'), ('de', 'German'), ('sq', 'Albanian')], default='', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('is_approved', False)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('is_approved', True)), _connector='OR'), name='media_asset_approval_state_is_complete'),
        ),
    ]
