# Generated by Django 6.1.1 on 2026-09-27 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_mediaasset_approved_at_mediaasset_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAcceptedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('exercise', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('left_text', models.CharField(max_length=250)),
                ('right_text', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('exercise', 'position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='external_id',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='external_id',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('picture_choice', 'Picture selection'), ('translation_choice', 'Translation choice'), ('missing_word', 'Missing word'), ('word_order', 'Word ordering'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('true_false', 'True or false'), ('dialogue_choice', 'Dialogue response'), ('free_text', 'Free-text translation'), ('matching', 'Matching pairs'), ('multiple_select', 'Multiple select')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('lesson', 'external_id'), name='unique_nonblank_exercise_external_id_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='unique_nonblank_media_external_id'),
        ),
        migrations.AddField(
            model_name='exerciseacceptedanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answers', to='courses.exercise'),
        ),
        migrations.AddField(
            model_name='matchingpair',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='courses.exercise'),
        ),
        migrations.AddConstraint(
            model_name='exerciseacceptedanswer',
            constraint=models.UniqueConstraint(fields=('exercise', 'text'), name='unique_accepted_answer_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='exerciseacceptedanswer',
            constraint=models.UniqueConstraint(fields=('exercise', 'position'), name='unique_accepted_answer_position_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='matchingpair',
            constraint=models.UniqueConstraint(fields=('exercise', 'position'), name='unique_matching_pair_position_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='matchingpair',
            constraint=models.UniqueConstraint(fields=('exercise', 'left_text', 'right_text'), name='unique_matching_pair_per_exercise'),
        ),
    ]
